# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.4.2

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-06-25T11:05:26Z"
  labels:
    app: my-website-pod
  name: my-website-pod
spec:
  containers:
  - args:
    - apache2-foreground
    image: localhost/my-php-app:latest
    name: my-website
    ports:
    - containerPort: 80
      hostPort: 8070
    volumeMounts:
    - mountPath: /var/www/html
      name: root-podman-cms-public-host-0
  volumes:
  - hostPath:
      path: /root/podman-cms/public
      type: Directory
    name: root-podman-cms-public-host-0

